calcitem/Sanmill

src/ui/flutter_app/lib/l10n/intl_es.arb

Greetings. I update the Spanish translation of this mill game to make it more consistent and easier to understand.

Update spanish translation

---

.github/workflows/dart-analyze.yml

https://github.com/ValentinVignal/action-dart-analyze

ci: Create dart-analyze.yml

---

src/ui/flutter_app/lib/mill/position.dart
src/ui/flutter_app/lib/screens/game_page/game_page.dart
src/ui/flutter_app/lib/screens/personalization_settings/point_style_modal.dart
src/ui/flutter_app/lib/shared/painters/board_painter.dart
src/ui/flutter_app/lib/shared/painters/pieces_painter.dart

We had a lot of old code behind comments. I've removed them for better readability of the code and easier maintenance (when searching stiff in the code it sometimes brings you to dead code ...)
also the methods on the gamePage observing the routes does only log "/" as we don't use namedRoutes

cleanup dead code

---

src/ui/flutter_app/lib/screens/about_page.dart
src/ui/flutter_app/lib/screens/env_page.dart
src/ui/flutter_app/lib/screens/game_page/game_page.dart
src/ui/flutter_app/lib/screens/game_settings/game_settings_page.dart
src/ui/flutter_app/lib/screens/help_screen.dart
src/ui/flutter_app/lib/screens/home.dart
src/ui/flutter_app/lib/screens/license_page.dart
src/ui/flutter_app/lib/screens/personalization_settings/personalization_settings_page.dart
src/ui/flutter_app/lib/screens/rule_settings/rule_settings_page.dart
src/ui/flutter_app/lib/shared/custom_drawer/src/icon.dart
src/ui/flutter_app/lib/shared/custom_drawer/src/widget.dart

regarding #358 I did fix a bug where the threshold wasn't calculated properly. I also implemented a a dependency to the sliding velocity to override the needed threshold. 
If the drawer is not right you should fine tune both thresholds (the one of the velocity and the drag one).

 fix some drawer stuff fixes #358 and fixes #351

---

src/ui/flutter_app/lib/screens/game_page/game_page.dart
src/ui/flutter_app/lib/screens/game_page/game_page_toolbar.dart

#328 should be fixed now :upside_down_face:

Game toolbar color

---

src/ui/flutter_app/lib/main.dart
src/ui/flutter_app/lib/shared/feedback_localization.dart

I'm not that happy with the way this is implemented and that it isn't integrated into our localization workflow...
this is a quick fix and something cleaner will come later

add feedback localizations fixes #357

---

.github/workflows/clang-format.yml
src/perfect/perfectAI.cpp

Reference:
https://github.com/RafikFarhad/clang-format-github-action
https://stackoverflow.com/questions/33258159/how-to-make-clang-format-skip-sections-of-c-code

ci: Add Clang Format Github Action

---

.github/workflows/spelling.yml

Do not trigger spelling bot when pushing.

ci: spelling: Do not trigger when pushing

---

.github/actions/spelling/expect.txt
.vscode/settings.json
tests/gtest/gtest.vcxproj
tests/gtest/gtest.vcxproj.filters
tests/gtest/pch.cpp
tests/gtest/pch.h
tests/gtest/stack_test.cpp
tests/gtest/test.cpp
tests/gtest/types_test.cpp

gtest: Add types and stack test

---

src/ui/flutter_app/lib/screens/home.dart
src/ui/flutter_app/lib/services/catcher.dart
src/ui/flutter_app/lib/shared/constants.dart

unifies the naming and purpose of the recipient constand

Cleanup constants

---

.github/workflows/clang-format.yml
.github/workflows/codeql-analysis.yml
.github/workflows/cui-on-macos.yml
.github/workflows/cui-on-ubuntu.yml
.github/workflows/cui-on-windows.yml
.github/workflows/dart-analyze.yml
.github/workflows/flutter.yml
.github/workflows/qt-on-windows.yml

Partly fix https://github.com/calcitem/Sanmill/issues/411

ci: Detect path and do not build on PR

---

gamewindow.ui
millgame.pro
millgame.vcxproj
millgame.vcxproj.filters
src/debug.h
src/endgame.cpp
src/hashmap.h
src/mills.cpp
src/search.cpp
src/test/test.cpp
src/thread.cpp
src/tt.cpp
src/ui/qt/boarditem.cpp
src/ui/qt/boarditem.h
src/ui/qt/game.cpp
src/ui/qt/game.h
src/ui/qt/gamescene.cpp
src/ui/qt/gamescene.h
src/ui/qt/gamewindow.cpp
src/ui/qt/movelistview.h
src/ui/qt/pieceitem.cpp
src/ui/qt/pieceitem.h

Refactor some code of Qt part.

Qt refactor

---

.github/workflows/clang-format.yml
.github/workflows/codeql-analysis.yml
.github/workflows/cui.yml
.github/workflows/flutter.yml
.github/workflows/qt-on-windows.yml

Run-on pulls are made directly onto the master or dev branch but only on PRs for the other branches.

ci: Change trigger conditions (#411)

---

.editorconfig
.github/actions/spelling/expect.txt
.run/Sanmill-monkey.run.xml
.run/Sanmill-test.run.xml
.vscode/launch.json
.vscode/settings.json
Readme.md
src/ui/flutter_app/lib/main.dart
src/ui/flutter_app/lib/screens/game_page/game_page.dart
src/ui/flutter_app/lib/services/environment_config.dart
src/ui/flutter_app/pubspec.yaml
tests/appium/.gitignore
tests/appium/Readme.md
tests/appium/package.json
tests/appium/test.js

Reference:
https://github.com/appium-userland/appium-flutter-driver
http://appium.io/docs/en/about-appium/getting-started/
https://dev.to/netfirms/flutter-app-testing-with-appium-flutter-driver-33ko

test: Support Appium

---

src/ui/flutter_app/lib/l10n/intl_en.arb
src/ui/flutter_app/lib/screens/game_settings/game_settings_page.dart

Move auto-restart option to misc card and restore the sound card
Revert playSounds removed by commit fcd8eae98fd9e97a6088cb508de2d06a465e5991

Preferences

---

flutter-init.sh
src/ui/flutter_app/lib/screens/about_page.dart
src/ui/flutter_app/lib/services/git_info.dart
src/ui/flutter_app/lib/shared/theme/app_theme.dart
src/ui/flutter_app/pubspec.yaml

This repository ("Code - OSS") is where Calcitem develops the Sanmill product together with the community, not only Calcitem. So need to remove the copyright text.
Show Git branch and revision on about dialog.

About page

---

.github/actions/spelling/expect.txt
src/bitboard.cpp
src/bitboard.h
src/mills.h

Fix SonarQube errors and warnings.

Fix vera++ and cppcheck errors

---

.github/workflows/cui.yml

ci: Update cui.yml

---

src/perfect/mill.cpp
src/perfect/mill.h
src/perfect/millAI.cpp
src/perfect/millAI.h
src/perfect/miniMax.cpp
src/perfect/miniMax.h
src/perfect/miniMax_alphaBetaAlgorithmn.cpp
src/perfect/miniMax_database.cpp
src/perfect/miniMax_retroAnalysis.cpp
src/perfect/miniMax_retroAnalysis.h
src/perfect/miniMax_statistics.cpp
src/perfect/miniMax_test.cpp
src/perfect/perfectAI.cpp
src/perfect/perfectAI.h
src/perfect/perfect_test.cpp

perfect: Refactor

---

.github/workflows/clang-format.yml
.github/workflows/codeql-analysis.yml
.github/workflows/cui.yml
.github/workflows/flutter.yml
.github/workflows/qt-on-windows.yml

- Only run CI if marked ready for review or a review is requested fixes
- This will disable the CI running on draft PRs.

change CI triggers fixes #411

---

CONTRIBUTING.md

Follow the requirements of https://bestpractices.coreinfrastructure.org/,
Information on how to contribute should include requirements for acceptable contributions.
Reference: https://llvm.org/docs/Contributing.html

CONTRIBUTING.md: Add content about ensuring PR is formatted properly

---

.vscode/settings.json
INSTALL.md

doc: Add INSTALL.md

---

README.md

README.md: Add badge of Weblate

README.md: Add badge of Weblate

---

.github/actions/spelling/expect.txt
src/ui/flutter_app/lib/screens/game_page/game_page_action_sheet.dart
src/ui/flutter_app/lib/screens/game_page/info_dialog.dart
src/ui/flutter_app/lib/screens/game_page/move_list_dialog.dart
src/ui/flutter_app/lib/shared/custom_drawer/src/item.dart
src/ui/flutter_app/lib/shared/theme/app_theme.dart

* Change font size
* Fix crash when entering move list (WAR)

Better utilize the MillController (3) 

---

src/ui/flutter_app/lib/main.dart
src/ui/flutter_app/lib/screens/game_page/move_list_dialog.dart
src/ui/flutter_app/lib/services/mill/src/history_navigation.dart
src/ui/flutter_app/lib/services/mill/src/position.dart
src/ui/flutter_app/lib/services/mill/src/recorder.dart
src/ui/flutter_app/lib/services/mill/src/types.dart
src/ui/flutter_app/lib/shared/iterable/pointed_list.dart
src/ui/flutter_app/lib/shared/scaffold_messenger.dart

Please refer to the Commit Message of each Git commit for the modification content and the reason for modification.

Modify the implementation of History navigation

---

src/ui/flutter_app/lib/screens/game_page/board.dart
src/ui/flutter_app/lib/screens/game_page/game_page.dart
src/ui/flutter_app/lib/screens/game_page/move_list_dialog.dart
src/ui/flutter_app/lib/screens/rule_settings/rule_settings_page.dart

On branch master (v1.1.43), game_page.dart:
Call initState() in Game.instance.init();
to call _position = Position(); to clean the board.
So follow it.
But now Position() does not call anything, why?
See master:
```dart
init() {
for (var i = 0; i < _grid.length; i++) {
_grid[i] = Piece.noPiece;
}
for (var i = 0; i < board.length; i++) {
board[i] = Piece.noPiece;
}
phase = Phase.placing;
setPosition(rule); // TODO
// TODO
recorder = GameRecorder(lastPositionWithRemove: fen());
}
Position() {
init();
}
```
Why not branch dev follow it? Why?

Fix some MillController bugs

---

src/ui/flutter_app/lib/screens/game_page/header.dart
src/ui/flutter_app/lib/shared/custom_drawer/custom_drawer.dart
src/ui/flutter_app/lib/shared/custom_drawer/src/widget.dart
src/ui/flutter_app/pubspec.yaml

Top drawer menu title

---

src/ui/qt/CMakeLists.txt

for
~~~
...
ui_gamewindow.h:30:10: fatal error: gameview.h: No such file or directory 
...
~~~

add 'src/ui/qt' to include directories

---

src/ui/flutter_app/lib/main.dart
src/ui/flutter_app/lib/shared/constants.dart

fix navigatorKey

---

src/ui/flutter_app/lib/main.dart
src/ui/flutter_app/lib/screens/game_page/game_page.dart
src/ui/flutter_app/lib/screens/game_page/header.dart
src/ui/flutter_app/lib/screens/home.dart
src/ui/flutter_app/lib/services/init_system_ui.dart
src/ui/flutter_app/lib/shared/painters/src/common.dart
src/ui/flutter_app/lib/shared/wizard/wizard_dialog.dart

…arge screen does not limit the orientation of the horizontal and vertical screens

The game interface is centered under the horizontal screen, and the large screen does not limit the orientation of the horizontal and vertical screens

---

src/ui/flutter_app/lib/shared/wizard/wizard_dialog.dart

fix wizard animation bug
